[all_follow]
nixpkgs = "nixpkgs"

[tack]
recomposable = true

[inputs.nixpkgs]
url = "github:NixOS/nixpkgs/nixos-unstable"

[inputs.bindiff]
url = "github:amaanq/bindiff"

[inputs.ida-pro-mcp]
url = "github:mrexodia/ida-pro-mcp"
type = "fetch"
